name: neep
channels:
  - defaults
dependencies:
  - python=3.6
  - pip:
    - torch
    - torchvision
    - numpy==1.16.1
    - tqdm
    - matplotlib
    - pandas
    - scipy
    - seaborn
    - jupyter
    - ipykernel